version: '3.4'

services:
  app:
    image: app
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "8000:8000"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    #   - ./redis.conf:/etc/redis/redis.conf
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
        - action: rebuild
          path: .
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./staticfiles:/usr/src/app/staticfiles
    ports:
      - "80:80"

  redis:
    image: redis:latest
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
  
# sever:
#   build:
#     context: ./weather_app
#     dockerfile: ./DockerFile
#   ports:
#     - "3000:3000"
#   develop:
#     watch:
#       - action: rebuild
#         path: ./weather_app