# Name of your Docker image
IMAGE_NAME = weather_app

# Name of your Docker container
CONTAINER_NAME = your-container-name #! needed (change)

# Your GitHub repository
GITHUB_REPO = https://github.com/nathan-perrier23/IA1-Weather-App-Django.git

# Build the Docker image
build:
    docker build -t $(IMAGE_NAME) -f dockerfile .

# Run the Docker container
run:
    docker run --name $(CONTAINER_NAME) -d -p 8000:8000 $(IMAGE_NAME)

# Stop the Docker container
stop:
    docker stop $(CONTAINER_NAME)

# Remove the Docker container
rm:
    docker rm $(CONTAINER_NAME)

# Push changes to GitHub
push:
    git add .
    git commit -m "Makefile Commit"
    git push origin master

# Connect the Docker container to the GitHub repository
connect: build run push