# Generated by Django 4.1.2 on 2024-03-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocationModel',
        ),
    ]
