# Generated by Django 4.1.2 on 2024-04-02 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256)),
                ('status_code', models.CharField(max_length=256)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(max_length=256)),
                ('gateway_transaction_id', models.CharField(max_length=256)),
                ('gateway_response', models.TextField()),
                ('gateway_response_code', models.CharField(max_length=256)),
                ('gateway_response_message', models.CharField(max_length=256)),
                ('gateway_response_time', models.DateTimeField(auto_now=True)),
                ('gateway_response_raw', models.TextField()),
                ('method', models.CharField(max_length=256)),
                ('method_transaction_id', models.CharField(max_length=256)),
                ('method_response', models.TextField()),
                ('method_response_code', models.CharField(max_length=256)),
                ('method_response_message', models.CharField(max_length=256)),
                ('method_response_time', models.DateTimeField(auto_now=True)),
                ('method_response_raw', models.TextField()),
                ('payment_details', models.TextField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.paymentstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.paymentstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('food_and_drinks', models.ManyToManyField(blank=True, to='events.foodanddrinks')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.payment')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingstatus')),
                ('tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tickets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vouchers', models.ManyToManyField(blank=True, to='events.voucher')),
            ],
        ),
    ]
