# Generated by Django 4.1.2 on 2024-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_tickets_booking_ticket_remove_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='aud', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_invoice_id',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
