# Generated by Django 4.1.2 on 2024-04-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_stripe_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='item',
        ),
    ]
