# Generated by Django 4.1.2 on 2024-04-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_payment_stripe_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='food_and_drinks',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vouchers',
        ),
    ]
