# Generated by Django 4.1.2 on 2024-04-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodanddrinks',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventfoodanddrinks'),
        ),
    ]
