# Generated by Django 4.1.2 on 2024-04-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_tickets',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
