# Generated by Django 4.1.2 on 2024-04-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_events_event_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_tickets',
        ),
    ]
