# Generated by Django 4.1.2 on 2024-04-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_events_event_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodanddrinksitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='food_and_drinks/'),
        ),
    ]
