# Generated by Django 4.1.2 on 2024-04-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_foodanddrinksitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodanddrinksitem',
            old_name='last_modification',
            new_name='last_modified',
        ),
    ]
