# Generated by Django 4.1.2 on 2024-04-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_last_modification_foodanddrinksitem_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='payment_link',
        ),
        migrations.AddField(
            model_name='events',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
