# Generated by Django 4.1.2 on 2024-04-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_events_payment_link_events_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodanddrinksitem',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
