# Generated by Django 4.1.2 on 2024-04-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_foodanddrinksitem_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='stripe_price_id',
        ),
    ]
