# Generated by Django 4.1.2 on 2024-04-07 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_food_and_drinks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_remove_voucher_stripe_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingVouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='BookingFoodAndDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('food_and_drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.foodanddrinks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
