# Generated by Django 4.1.2 on 2024-04-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_events_food_and_drinks_remove_events_vouchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='schedule',
        ),
    ]
