# Generated by Django 4.1.2 on 2024-04-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_events_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodanddrinksitem',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
