# Generated by Django 4.1.2 on 2024-04-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_foodanddrinksitem_event_voucher_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvoucher',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
