# Generated by Django 4.1.2 on 2024-04-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_voucher_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodanddrinksitem',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
