# Generated by Django 4.1.2 on 2024-04-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_foodanddrinksitem_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='stripe_cod_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
