# Generated by Django 4.1.2 on 2024-04-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_voucher_stripe_cod_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='stripe_cod_id',
            new_name='stripe_code_id',
        ),
    ]
