# Generated by Django 4.1.2 on 2024-04-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_rename_stripe_cod_id_voucher_stripe_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
