# Generated by Django 4.1.2 on 2024-04-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_events_description_alter_events_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
