# Generated by Django 4.1.2 on 2024-04-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_events_target_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvoucher',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
    ]
