# Generated by Django 4.1.2 on 2024-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_eventvoucher_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
