# Generated by Django 4.1.2 on 2024-01-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
