# Generated by Django 4.1.2 on 2024-01-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='ip',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
