# Generated by Django 4.1.2 on 2024-01-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atc_site', '0004_alter_registerauth_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_code', models.CharField(max_length=6)),
                ('expiration_time', models.DateTimeField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atc_site.customuser')),
            ],
        ),
    ]
