# Generated by Django 4.1.2 on 2024-01-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc_site', '0005_forgotpasswordauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('region_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=10)),
                ('isp', models.CharField(max_length=100)),
            ],
        ),
    ]
