# Generated by Django 4.1.2 on 2024-01-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc_site', '0006_userlocationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocationmodel',
            name='ip',
            field=models.CharField(max_length=256),
        ),
    ]
