# Generated by Django 4.1.2 on 2024-01-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc_site', '0007_alter_userlocationmodel_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('city', models.TextField()),
                ('zip', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('image_url', models.TextField()),
                ('is_safe', models.BooleanField(default=False)),
            ],
        ),
    ]
