# Generated by Django 4.1.2 on 2024-01-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc_site', '0008_locationimagesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationimagesmodel',
            name='zip',
        ),
        migrations.AlterField(
            model_name='locationimagesmodel',
            name='image_url',
            field=models.ImageField(upload_to='images/ai_images/'),
        ),
    ]
