# Generated by Django 4.1.2 on 2024-01-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atc_site', '0009_remove_locationimagesmodel_zip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
