# Generated by Django 4.1.2 on 2024-02-07 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("atc_site", "0011_alter_forgotpasswordauth_reset_code_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LocationImagesModel",
        ),
    ]
