# Generated by Django 4.1.2 on 2024-02-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atc_site", "0012_delete_locationimagesmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationImagesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=200)),
                ("city", models.TextField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("image_url", models.ImageField(upload_to="images/ai_images/")),
                ("is_safe", models.BooleanField(default=False)),
            ],
        ),
    ]
