# Generated by Django 4.1.2 on 2024-03-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotATC', '0001_initial'),
    ]

    operations = [
    ]
